# Generated by Django 4.1.5 on 2023-02-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_date_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-date_issue', 'title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
