# Generated by Django 4.1.5 on 2023-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_books_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(default=1, upload_to='icon_category', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
