# Generated by Django 4.1.7 on 2023-02-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Человекопонятный URL (само генерация)')),
                ('image', models.ImageField(upload_to='image_author/', verbose_name='Фото Автора')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['date_issue'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
