# Generated by Django 4.1.7 on 2023-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_author_alter_books_options_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='image_author/', verbose_name='Фото Автора'),
        ),
    ]
