# Generated by Django 4.1.7 on 2023-03-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='dowl',
            field=models.BooleanField(default=True, verbose_name='Разрешение на скачевание'),
        ),
    ]
