# Generated by Django 4.1.7 on 2023-03-06 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0008_books_dowl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='dowl',
        ),
        migrations.AddField(
            model_name='books',
            name='buyer',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='покупатели'),
        ),
    ]
