# Generated by Django 3.2.18 on 2023-03-08 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0009_remove_books_dowl_books_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='buyer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='покупатели'),
        ),
    ]
