# Generated by Django 5.0.3 on 2024-03-30 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_books_buyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='image_author/', verbose_name='фото автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=70, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
                ('book', models.FileField(upload_to='book/', verbose_name='файл книги')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='book_image/', verbose_name='фото')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление в сайт')),
                ('date_issue', models.DateField(null=True, verbose_name='дата выпуска книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='автор')),
                ('category', models.ManyToManyField(to='book.category', verbose_name='категории')),
                ('favorite', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='В любимых')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('date_issue',),
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
