# Generated by Django 5.0.3 on 2024-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_author_description_author_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='book.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='book.author', verbose_name='автор'),
        ),
    ]
