# Generated by Django 4.1.5 on 2023-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.FileField(upload_to='logo/', verbose_name='логотип сайта')),
            ],
        ),
    ]
